package com.yourname.blog.Blog.controller;
import com.yourname.blog.Blog.dto.*; import com.yourname.blog.Blog.entity.*; import com.yourname.blog.Blog.repository.*; import com.yourname.blog.Blog.service.ArticleMapper; import jakarta.validation.Valid; import jakarta.transaction.Transactional; import lombok.RequiredArgsConstructor; import org.springframework.data.domain.*; import org.springframework.http.*; import org.springframework.security.core.context.SecurityContextHolder; import org.springframework.web.bind.annotation.*; import java.util.*;
@RestController @RequestMapping("/api/articles") @RequiredArgsConstructor public class ArticleController { private final BlogRepository blogs; private final UserRepository users; private final CommentRepository comments; private final ArticleMapper mapper;
 private User me(){return users.findByEmail(SecurityContextHolder.getContext().getAuthentication().getName()).orElseThrow(()->new RuntimeException("User not found"));}
 @GetMapping @Transactional public Page<ArticleResponse> feed(@RequestParam(defaultValue="0")int page,@RequestParam(defaultValue="10")int size){return blogs.findAll(PageRequest.of(page,size,Sort.by("createdAt").descending())).map(mapper::map);}
 @GetMapping("/{id}") @Transactional public ArticleResponse article(@PathVariable Long id){return mapper.map(blogs.findById(id).orElseThrow(()->new RuntimeException("Article not found")));}
 @GetMapping("/search") @Transactional public List<ArticleResponse> search(@RequestParam String q){return blogs.findByTitleContainingIgnoreCaseOrContentContainingIgnoreCase(q,q).stream().map(mapper::map).toList();}
 @GetMapping("/mine") @Transactional public List<ArticleResponse> mine(){return blogs.findByAuthor(me()).stream().map(mapper::map).toList();}
 @PostMapping public ResponseEntity<ArticleResponse> create(@Valid @RequestBody BlogRequest r){Blog b=Blog.builder().title(r.getTitle()).content(r.getContent()).author(me()).build();return ResponseEntity.status(HttpStatus.CREATED).body(mapper.map(blogs.save(b)));}
 @PutMapping("/{id}") @Transactional public ArticleResponse edit(@PathVariable Long id,@Valid @RequestBody BlogRequest r){Blog b=blogs.findById(id).orElseThrow(()->new RuntimeException("Article not found"));if(!b.getAuthor().getId().equals(me().getId()))throw new RuntimeException("You can only edit your own stories");b.setTitle(r.getTitle());b.setContent(r.getContent());return mapper.map(blogs.save(b));}
 @DeleteMapping("/{id}") @Transactional public ResponseEntity<Void> delete(@PathVariable Long id){Blog b=blogs.findById(id).orElseThrow(()->new RuntimeException("Article not found"));if(!b.getAuthor().getId().equals(me().getId()))throw new RuntimeException("You can only delete your own stories");blogs.delete(b);return ResponseEntity.noContent().build();}
 @GetMapping("/{id}/comments") public List<CommentResponse> comments(@PathVariable Long id){Blog b=blogs.findById(id).orElseThrow(()->new RuntimeException("Article not found"));return comments.findByBlog(b).stream().map(c->new CommentResponse(c.getId(),c.getContent(),c.getUser().getName(),c.getCreatedAt())).toList();}
 @PostMapping("/{id}/comments") public CommentResponse comment(@PathVariable Long id,@RequestBody CommentRequest r){Blog b=blogs.findById(id).orElseThrow(()->new RuntimeException("Article not found"));Comment c=comments.save(Comment.builder().blog(b).user(me()).content(r.getContent()).createdAt(java.time.LocalDateTime.now()).build());return new CommentResponse(c.getId(),c.getContent(),c.getUser().getName(),c.getCreatedAt());}
}
